### ISSUE TITLE
Need a way to reset a cache

### ISSUE THREAD

**Issue by SVilgelm** [illikainen/ossaudit#3]
I case of the index DB is updated (a vulnerability is fixed) the `ossaudit` tool uses the data from the cache and doesn't fetch new records.
To get new data I had to find and remove the `cache.json` file.
It would be great to have a flag `--no-cache` to ignore the data from `cache.json` or `--reset-cache` to rewrite the cache file.

**Comment by illikainen** [comment]
Thanks for the suggestion!

Master now has support for `--reset-cache` to remove any existing cache before `ossaudit` collects vulnerability data.  It also has support for `--ignore-cache` (I went with `--ignore-` as opposed to `--no-` since we already have an `--ignore-id` knob) to temporarily ignore the cache (i.e. that nothing is read from or written to the cache with this option).

**Comment by SVilgelm** [comment]
Great, thank you
